&copy; 2019 by Pearson Education, Inc. All Rights Reserved. The content in this notebook is based on the book [**Python for Programmers**](https://amzn.to/2VvdnxE).

# 7. Array-Oriented Programming with NumPy

# 7.1 Introduction
* `numpy` module’s high-performance `ndarray`.
* How `ndarray`s differ from lists.
* Compare list and `ndarray` performance with the **IPython `%timeit` magic**.
* Common `ndarray` manipulations.
* Multidimensional `ndarray`s.

### **NumPy** (**Numerical Python**) Library
* First appeared in 2006 and is the **preferred Python array implementation**.
* High-performance, richly functional **_n_-dimensional array** type called **`ndarray`**. 
* **Written in C** and **up to 100 times faster than lists**.
* Critical in big-data processing, AI applications and much more. 
* According to `libraries.io`, **over 450 Python libraries depend on NumPy**. 
* Many popular data science libraries such as Pandas, SciPy (Scientific Python) and Keras (for deep learning) are built on or depend on NumPy. 

### Array-Oriented Programming
* **Functional-style programming** with **internal iteration** makes array-oriented manipulations concise and straightforward, and reduces the possibility of error.

# 7.2 Creating `array`s from Existing Data 
### Creating an Array with the **`array`** Function 
* Argument is an `array` or other iterable.
* Returns a new `array` containing the argument’s elements.

In [1]:
import numpy as np  # np recommended by the docs

In [2]:
numbers = np.array([2, 3, 5, 7, 11])  # arrays store elements of the same type

In [3]:
type(numbers)

numpy.ndarray

### Array `__repr__` and `__str__` Representations

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

In [5]:
str(numbers)

'[ 2  3  5  7 11]'

### Multidimensional Arguments

In [6]:
np.array([[1, 2, 3], 
          [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

# 7.3 `array` Attributes 

In [7]:
integers = np.array([[1, 2, 3], 
                     [4, 5, 6]])

In [8]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [10]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

### Determining an `array`’s Element Type with the **`dtype`** Attribute

In [11]:
integers.dtype

dtype('int64')

In [12]:
floats.dtype

dtype('float64')

### Other NumPy Types
* [NumPy types](https://docs.scipy.org/doc/numpy/user/basics.types.html)

### Determining an `array`’s Dimensions with **`ndim`** and **`shape`** 

In [13]:
integers.ndim

2

In [14]:
floats.ndim

1

In [15]:
integers.shape

(2, 3)

In [16]:
floats.shape

(5,)

### `array`’s **`size`** (Number of Elements) and **`itemsize`** (Bytes Per Element)

In [17]:
integers.size  # number of elements

6

In [18]:
integers.itemsize  # 4 bytes for C compilers that use 32-bit ints

8

In [19]:
floats.size

5

In [20]:
floats.itemsize

8

### Iterating Through a Multidimensional `array`’s Elements

In [21]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print()

1  2  3  
4  5  6  


### Iterating Through a 2D Array via **`flat`** 

In [22]:
for i in integers.flat:  # one-dimensional view of integers
    print(i, end='  ')

1  2  3  4  5  6  

# 7.5 Creating `array`s from Ranges 
### Creating Integer Ranges with `arange` 

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [25]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

### Creating Evenly Spaced Floating-Point Ranges with `linspace` 
* Starting and ending values in the range are **inclusive**.
* **`num`** specifies the **number of evenly spaced values** to produce—**default is 50**.

In [26]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshaping an `array` with Method **`reshape`**
* New shape **must** be the **same number of elements** as the original. 

In [27]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Displaying `array`s with 1000+ Items Drops from the Output the Middle Rows, Columns or Both
* [This and many other print options are customizable](https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html).

In [28]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

# 7.6 List vs. `array` Performance: Introducing `%timeit` 
### Timing the Creation of a List of 6,000,000 Die Rolls 
* The **`%timeit` magic** executes a statement in a loop and **runs the loop seven times**. 
* In our testing, operations that on average took more than 500 milliseconds iterated only once per loop, and operations that took fewer than 500 milliseconds iterated 10 times or more per loop. 
* After executing the statement, `%timeit` displays the statement’s **average execution time** over all executions. 

In [29]:
import random

In [30]:
%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]

5.08 s ± 50.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Timing the Creation of an `array` Containing Results of 6,000,000 Die Rolls 
* The **`randint` function** from the **`numpy.random` module** generates values in a range from its first argument up to but not including its second argument. 

In [31]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)  # 6,000,000 1-6 values

50.6 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Customizing the `%timeit` Iterations
* See the [IPython magics documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html) for controlling the number of runs and number of iterations per run, as well as the dozens of other magics for a variety of tasks.
* **`%%timeit`** can be used to time **all the code in a cell** rather than just one statement.

# 7.7 `array` Operators
* `array` operators perform operations on **entire `array`s**. 
* Can perform arithmetic **between `array`s and scalar numeric values**, and **between `array`s of the same shape**.

### Element-wise Arithmetic Operations with `array`s and Individual Numeric Values

In [32]:
numbers = np.arange(1, 6)

In [33]:
numbers

array([1, 2, 3, 4, 5])

In [34]:
numbers * 2  # multiply every element by 2, creating a new array

array([ 2,  4,  6,  8, 10])

In [35]:
numbers  # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

### Augmented Assignments **Modify Every Element in the Left Operand**

In [36]:
numbers += 10  # add 10 to every element, modifying the original array

In [37]:
numbers

array([11, 12, 13, 14, 15])

### Broadcasting 
* Arithmetic operations require as operands two `array`s of the **same size and shape**. 
* **`numbers * 2`** is equivalent to **`numbers * [2, 2, 2, 2, 2]`** for a 5-element array.
* Applying the operation to every element is called **broadcasting**. 
* Also can be applied between `array`s of different sizes and shapes, enabling some concise and powerful manipulations.

### Arithmetic Operations Between `array`s of the Same Shape

In [38]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [39]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [40]:
numbers

array([11, 12, 13, 14, 15])

In [41]:
numbers * numbers2  # element-by-element multiplication

array([12.1, 26.4, 42.9, 61.6, 82.5])

### Comparing `array`s Element-Wise with Individual Values and with Other `array`s Produce **`array`s of Boolean Values**

In [42]:
numbers

array([11, 12, 13, 14, 15])

In [43]:
numbers >= 13

array([False, False,  True,  True,  True])

In [44]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [45]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

# 7.8 NumPy Calculation Methods
* These methods **ignore the `array`’s shape** and **use all the elements in the calculations**. 
* Consider an `array` representing four students’ grades on three exams:

In [46]:
grades = np.array([[87, 96, 70], 
                   [100, 87, 90],
                   [94, 77, 90], 
                   [100, 81, 82]])

In [47]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

### Some of `ndarray`'s Functional-Style Reductions

In [48]:
grades.sum()

1054

In [49]:
grades.min()

70

In [50]:
grades.max()

100

In [51]:
grades.mean()

87.83333333333333

### Calculations By Column
* You can perform calculations by column or row (or other dimensions in arrays with more than two dimensions).
* Each 2D+ array has [**one axis per dimension**](https://docs.scipy.org/doc/numpy-1.16.0/glossary.html).
* In a 2D array, **`axis=0`** indicates calculations should be **column-by-column**.

In [52]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [53]:
grades.mean(axis=0)  # average grade on each exam (column)

array([95.25, 85.25, 83.  ])

### Calculations By Row
*  In a 2D array, **`axis=1`** indicates calculations should be **row-by-row**. 

In [54]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [55]:
grades.mean(axis=1)  # average grade for each student (row)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

### Other NumPy `array` Calculation Methods
* [Calculation Methods](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)

# 7.9 Universal Functions
* Standalone [**universal functions** (**ufuncs**)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) perform **element-wise operations** using one or two `array` or array-like arguments (like lists). 
* Each returns a **new `array`** containing the results.
* Some ufuncs are called when you use `array` operators like `+` and `*`. 

### Calculate the Square Roots of an `array`'s Values with the **`sqrt` Universal Function**

In [56]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [57]:
np.sqrt(numbers)  # array-oriented programming

array([1., 2., 3., 4., 5., 6.])

### Add Two `array`s Using the **`add` Universal Function**

In [58]:
numbers2 = np.arange(1, 7) * 10

In [59]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [60]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [61]:
np.add(numbers, numbers2)  # equivalent to numbers + numbers2

array([11, 24, 39, 56, 75, 96])

### Broadcasting Also Works with Universal Functions

In [62]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [63]:
np.multiply(numbers2, 5)  # equivalent to numbers2 * 5

array([ 50, 100, 150, 200, 250, 300])

* Reshape `numbers2` into a 2-by-3 `array`, then multiply its values by a one-dimensional `array` of three elements

In [64]:
numbers3 = numbers2.reshape(2, 3)

In [65]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [66]:
numbers4 = np.array([2, 4, 6]) 

In [67]:
np.multiply(numbers3, numbers4)  # multiply each row of numbers3 by numbers4

array([[ 20,  80, 180],
       [ 80, 200, 360]])

### Broadcasting Rules
* [Broadcasting rules documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

### Scores of Other Universal Functions
* **Math**, **trigonometry**, **bit manipulation**, **comparison** and **floating point** [universal functions documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)

# 7.10 `array` Indexing and Slicing 
* One-dimensional `array`s can be **indexed** and **sliced** like lists. 

### Indexing Two-Dimensional `array`s Requires a Tuple in Square Brackets

In [68]:
grades = np.array([[87, 96, 70], 
                   [100, 87, 90],
                   [94, 77, 90], 
                   [100, 81, 82]])

In [69]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [70]:
grades[0, 1]  # 0, 1 is a tuple representing row 0 and column 1

96

### Selecting a Subset of a Two-Dimensional `array`’s Rows

In [71]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [72]:
grades[1]  # select row 1

array([100,  87,  90])

In [73]:
grades[0:2]  # select rows 0 through 1

array([[ 87,  96,  70],
       [100,  87,  90]])

In [74]:
grades[[1, 3]]  # the list [1, 3] selects rows 1 and 3

array([[100,  87,  90],
       [100,  81,  82]])

### Selecting a Subset of a Two-Dimensional `array`’s Columns
* The **column index** also can be a specific **index**, a **slice** or a **list**. 

### Select Only the Elements in the First Column

In [75]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [76]:
grades[:, 0]  # all rows (:) of column 0

array([ 87, 100,  94, 100])

### Select Consecutive Columns Using a **Slice**

In [77]:
grades[:, 1:3]  # all rows (:) of columns 1-2

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

### Select Specific Columns Using a **List of Column Indices**

In [78]:
grades[:, [0, 2]]  # all rows (:) of columns 0 and 2

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

# 7.13 Reshaping and Transposing 

### **Transposing** Rows and Columns
* “Flips” the `array`, so the rows become the columns and the columns become the rows. 
* **`T` attribute** returns a transposed **view (shallow copy)** of the `array`. 


In [79]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [80]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [ ]:
grades.T

# More Info 
* See Lesson 7 in [**Python Fundamentals LiveLessons** here on Safari Online Learning](https://learning.oreilly.com/videos/python-fundamentals/9780135917411)
* See Chapter 7 in [**Python for Programmers** on Safari Online Learning](https://learning.oreilly.com/library/view/python-for-programmers/9780135231364/)
* Interested in a print book? Check out:

| Python for Programmers | Intro to Python for Computer<br>Science and Data Science
| :------ | :------
| <a href="https://amzn.to/2VvdnxE"><img alt="Python for Programmers cover" src="../images/PyFPCover.png" width="150" border="1"/></a> | <a href="https://amzn.to/2LiDCmt"><img alt="Intro to Python for Computer Science and Data Science: Learning to Program with AI, Big Data and the Cloud" src="../images/IntroToPythonCover.png" width="159" border="1"></a>

>Please **do not** purchase both books&mdash;_Python for Programmers_ is a subset of _Intro to Python for Computer Science and Data Science_

&copy; 2019 by Pearson Education, Inc. All Rights Reserved. The content in this notebook is based on the book [**Python for Programmers**](https://amzn.to/2VvdnxE).